### ISSUE TITLE
Bannis de vinted

### ISSUE THREAD

**Issue by judzk** [Xen0o2/vinted-monitor#2]
Hello, j'ai laissé tourné le bot ce matin pendant un petit moment, je me suis mangé un ban :/
<img width="502" alt="image" src="https://user-images.githubusercontent.com/26792639/207595015-e28deb2b-8ba9-4c5e-a63d-dd48d677dba5.png">

Une idée pour limiter la casse?

**Comment by Xen0o2** [comment]
Salut @judzk, comment as-tu obtenu un screen d'une page de bannissement Vinted alors que le module ne propose aucune interface graphique avec le site ? De plus, après une longue utilisation de ma part, ainsi que d'autres nombreux utilisateurs, je n'ai jamais constaté aucun bannissement, es-tu sur de l'utiliser correctement ?

**Comment by judzk** [comment]
Hello, je ne suis pas du tout sur de l'utiliser correctement, mais j'ai juste utiliser ton exemple pour l'instant. Que j'envoi vers un bot discord :
`
Monitor.onItemFound(item => {
  const embed = new MessageBuilder()
  .setTitle(item.info.title)
  .setURL(item.info.url)
  .addField('Prix', item.info.price, true)
  .addField('Second field', 'this is not inline')
  .setColor('#00b0f4')
  // .setThumbnail(item.info.photo.url)
  .setDescription(item.info.description)
  .setImage(item.info.photo.url)
  // .setFooter('Hey its a footer', 'https://cdn.discordapp.com/embed/avatars/0.png')
  .setTimestamp();
  hook.send(embed);
})
`
Pour le screen, c'est le script qui m'a renvoyé un code HTML, je l'ai juste collé dans un fichier HTML pour faire mon script.
En tout cas merci pour ton boulot :)

**Comment by Xen0o2** [comment]
Combien d'URL observes-tu avec le module ?

**Comment by judzk** [comment]
Juste une seule, le ban est arrivé peu de temps apres la découverte du module, donc j'ai pas trop eu le temps d'approfondir. J'avais juste dockerisé le tout et laissé tourner dernière. Peut etre que j'ai fais tourner les 2 en simu sans le faire expres. Mais 24h après j'étais encore ban, je vais essayer après

**Comment by Xen0o2** [comment]
Même en laissant tourner le script en plusieurs exemplaires, ce n'est pas normal de se faire bannir avec simplement une URL. Essaye en changeant d'IP ou en virtualisant le tout.

Malheureusement je n'ai encore jamais été confronté au problème donc je ne vois pas d'où cela peut venir pour l'instant. Je ferais des recherches de mon côté pour voir si je peux apporter une mise à jour ^^ J'espère que d'autres personnes pourront venir t'aider si le problème persiste.

**Comment by judzk** [comment]
Alors j'ai relancé le script, toujours pareil, par contre peut etre un piste de recherche.
L'url via mon navitageur, pas de soucis ca passe, via le script ca plante :
Et quand je regarde le détail du retour il m'indique :
> Error reference number: 1020
> Server ID: FL_534F70
> User-Agent: node-fetch/1.0 (+https://github.com/bitinn/node-fetch)

Donc peut être qu'en jouant avec le user-agent ca devrait pouvoir contourner le soucis

**Comment by judzk** [comment]
Bon, c'est moi qui faisait nimps dans ma variable pour le bot discord ( mauvais copié collé ), et du coup vinted m'envoyé un message comme quoi j'étais banni.
Tout est corrigé, désolé pour le temps perdu
